algoritmo "semnome"
var
 n1, n2: inteiro
inicio
Escreva ("Digite um número inteiro: ")
Leia (n1)
Escreva ("Digite mais um numero inteiro: ")
Leia (n2)
     Se n1 > n2 entao
     escreva ("O primeiro valor é maior")
     senao
          se n2 > n1 entao
             escreva ("O segundo valor é maior")
             senao
                  escreva ("Os dois valores são iguais")
          FimSe
     FimSe
fimalgoritmo
