algoritmo "semnome"
var
metro, km, hm, dam, dm, cm, mm : real
inicio
Escreva ("Digire uma altura em Metros (m): ")
Leia (metro)
km <- metro/1000
hm <- metro/100
dam <- metro/10
dm <- metro*10
cm <- metro * 100
mm <- metro *1000
Escreval ("A distância de ", metro, " metros corresponde à: ")
Escreval (km, " Km")
Escreval (hm, " Hm")
Escreval (dam, " Dam")
Escreval (dm, " Dm")
Escreval (cm, " Cm")
Escreval (mm, " mm")
fimalgoritmo
